import os
from reportlab.lib.pagesizes import letter
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Image, Table, TableStyle
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib import colors
from app.core.config import settings

def generate_pdf_report(case_data: dict, user_email: str, user_role: str) -> str:
    case_id = str(case_data.get('id'))
    report_filename = f"report_{case_id}.pdf"
    
    # Ensure directory exists
    case_dir = os.path.join(settings.UPLOAD_DIR, case_id)
    os.makedirs(case_dir, exist_ok=True)
    report_path = os.path.join(case_dir, report_filename)
    
    doc = SimpleDocTemplate(report_path, pagesize=letter)
    styles = getSampleStyleSheet()
    elements = []
    
    # Title
    title_style = ParagraphStyle(
        'CustomTitle',
        parent=styles['Heading1'],
        fontSize=24,
        spaceAfter=14,
        textColor=colors.darkblue
    )
    elements.append(Paragraph("CyberShield AI Forensic Report", title_style))
    elements.append(Spacer(1, 12))
    
    # Summary
    elements.append(Paragraph(f"<b>Case ID:</b> {case_id}", styles['Normal']))
    elements.append(Paragraph(f"<b>Analyst:</b> {user_email} ({user_role})", styles['Normal']))
    elements.append(Paragraph(f"<b>Type:</b> {case_data.get('case_type', 'N/A').upper()}", styles['Normal']))
    elements.append(Spacer(1, 12))
    
    # Verdict & Confidence
    elements.append(Paragraph(f"<b>Overall Verdict:</b> {case_data.get('verdict', 'N/A').upper()}", styles['Heading3']))
    elements.append(Paragraph(f"<b>Confidence:</b> {case_data.get('confidence', 0) * 100:.1f}%", styles['Normal']))
    elements.append(Paragraph(f"<b>Risk Level:</b> {case_data.get('risk_level', 'N/A').upper()}", styles['Normal']))
    elements.append(Spacer(1, 24))
    
    # Footer
    elements.append(Paragraph("Generated by CyberShield AI | Confidential", styles['Italic']))
    
    doc.build(elements)
    return report_path
